services:
    sdd.transport.transport.email.sparkpost:
        class: SDD\Bundle\SparkPostTransportBundle\Transport\Email\MailTransport
        tags:
            - { name: ds.transport, implementation: email.sparkpost }
